//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetAllocations
    {
        public int AllocationID { get; set; }
        public int YearID { get; set; }
        public int ItemID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual BudgetItems BudgetItems { get; set; }
        public virtual FinancialYears FinancialYears { get; set; }
    }
}
