//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salariess
    {
        public int SalaryID { get; set; }
        public int EmployeeID { get; set; }
        public int YearID { get; set; }
        public int Month { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual FinancialYears FinancialYears { get; set; }
    }
}
